# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: c
#python:
#    - 3.3
#    - 3.4

install:
    - git clone --depth=50 --branch=master git://github.com/gramps-project/gramps.git gramps-project/gramps
    - cd gramps-project/gramps 
    - time sudo apt-get update
    - travis_retry sudo apt-get install gir1.2-pango gir1.2-gtk xdg-utils librsvg2-common libglib2.0-dev intltool 
    - travis_retry sudo apt-get install python3-gobject python3-gi python3-cairo python3-gi-cairo python3-bsddb3 python3-dev python3-nose

    - travis_retry curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    - travis_retry sudo pip3 install Django==1.7
    - travis_retry sudo pip3 install pyicu
    - travis_retry sudo pip3 install mock
    - python3 setup.py build

#before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99

script:
    -  mkdir -p /home/travis/.gramps/grampsdb/
    -  DJANGO_SETTINGS_MODULE=gramps.webapp.settings nosetests3 --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  gramps
